// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_getClientId from "./routes/api/getClientId.ts";
import * as $api_tts from "./routes/api/tts.ts";
import * as $api_upload_recording from "./routes/api/upload-recording.ts";
import * as $index from "./routes/index.tsx";
import * as $ChatIsland from "./islands/ChatIsland.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Menu from "./islands/Menu.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/getClientId.ts": $api_getClientId,
    "./routes/api/tts.ts": $api_tts,
    "./routes/api/upload-recording.ts": $api_upload_recording,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatIsland.tsx": $ChatIsland,
    "./islands/Header.tsx": $Header,
    "./islands/Menu.tsx": $Menu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
