services:
  school-bud-e-frontend:
    image: denoland/deno:latest
    container_name: school-bud-e-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "apt-get update && apt-get install -y git && git clone https://github.com/LAION-AI/school-bud-e-frontend.git && cd school-bud-e-frontend && deno task build && deno task preview"