services:
  school-bud-e-frontend:
    image: denoland/deno:latest
    container_name: school-bud-e-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/school-bud-e-frontend
    command: sh -c "apt-get update && apt-get install -y git && git clone https://github.com/LAION-AI/school-bud-e-frontend.git && cd school-bud-e-frontend && deno task build && deno run --allow-net --allow-read dist/main.js"

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
