  webhook:
    image: docker:latest
    container_name: webhook
    privileged: true
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    env_file:
      - .env
    volumes:
      - ./webhook:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
    network_mode: host
    restart: unless-stopped