services:
  webhook:
    image: docker:latest
    container_name: webhook
    privileged: true
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./webhook:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: apk update && apk add deno && tail -f /dev/null
    network_mode: host
    restart: unless-stopped