services:
  webhook:
    image: docker:latest
    container_name: webhook
    privileged: true
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - ./webhook:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "apk update && apk add deno && deno run --allow-env --allow-net --allow-run /app/webhook.ts"
    network_mode: host
    restart: unless-stopped